# Config file for {{ cookiecutter.project_slug }}
# Drop all relevant paths, parameters, etc. here
# They can be accessed in the code via:
#   from {{ cookiecutter.project_slug }}.config import path_to, params

PROJECT_NAME = "{{ cookiecutter.project_slug }}"

# all paths are relative to the PROJECT_ROOT folder named PROJECT_NAME
[paths]
DATA = "./data"
RESULTS = "./results"
CACHE = "./data/cache"
    [paths.results]
    GLM = "./results/glm"

[params]
weight_decay = 0.01

# Follwing creates arrays of tables
# [[tester]]
# id = 3
# name = "Nomis"
#
# [[tester]]
# id = 2
# name = "Divad"

# Note store private configs in same folder: "./[PRIVATE_PREFIX]_configs.toml"
